server:
  port: 3256
spring:
  datasource:
    url: jdbc:mysql://localhost:5689/SPEC?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false

